# Generated by Django 5.0.7 on 2024-07-20 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.CharField(max_length=255)),
                ('habits', models.TextField()),
                ('sleep_pattern', models.CharField(max_length=50)),
                ('smoking', models.CharField(max_length=50)),
                ('drinking', models.CharField(max_length=50)),
                ('diet', models.CharField(max_length=50)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
