# Generated by Django 5.0.7 on 2024-07-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='drinking',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='habits',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='smoking',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='career_domain',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cooking_skills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='degree_type',
            field=models.CharField(blank=True, choices=[('Masters', 'Masters'), ('PHD', 'PHD')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='guest_frequency',
            field=models.CharField(blank=True, choices=[('Sometimes', 'Sometimes'), ('More often', 'More often')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobbies_interests',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='looking_for_roommate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personality',
            field=models.CharField(blank=True, choices=[('Introvert', 'Introvert'), ('Extrovert', 'Extrovert'), ('Ambivert', 'Ambivert')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smoking_drinking',
            field=models.CharField(blank=True, choices=[('Occasionally', 'Occasionally'), ('Sometimes', 'Sometimes'), ('More often', 'More often')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='travel_pattern',
            field=models.CharField(blank=True, choices=[('Sometimes', 'Sometimes'), ('More often', 'More often')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='diet',
            field=models.CharField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Non-vegetarian', 'Non-vegetarian'), ('Vegan', 'Vegan')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pet_friendly',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sleep_pattern',
            field=models.CharField(blank=True, choices=[('Morning person', 'Morning person'), ('Night owl', 'Night owl')], max_length=50, null=True),
        ),
    ]
